const std = @import("std");

pub const feature_flag = struct {
    pub const leaf: u32 = 1;
    pub const reg: usize = 3;
    pub const bit: u5 = 0;
};

pub const Opcode = enum(u16) {
    fadd,
    fdiv,
    fdivr,
    fcom,
    fcomp,
    fsub,
    fsubr,
    fmul,
    fiadd,
    fidiv,
    fisub,
    fimul,
    ficom,
    ficomp,
    fld,
    fst,
    fstp,
    fild,
    fist,
    fistp,
    fcompp,
    fucom,
    fucomp,
    fucompp,
    fchs,
    fabs,
    ftst,
    fxam,
    fld1,
    fldl2t,
    fldl2e,
    fldpi,
    fldlg2,
    fldln2,
    fldz,
    f2xm1,
    fyl2x,
    fptan,
    fpatan,
    fxtract,
    fprem1,
    fdecstp,
    fincstp,
    fprem,
    fyl2xp1,
    fsqrt,
    fsincos,
    frndint,
    fscale,
    fsin,
    fcos,
    fwait,
    fnop,
    fclex,
    fstsw,
    fstcw,
    fldcw,
    fldenv,
    fsave,
    frstor,
    finit,
    fbld,
    fbstp,
    fxch,
    fnstenv,
    fnstsw,
    fnstcw,
    ffree,
};

const Enc = struct {
    mnemonic: []const u8,
    opcode: u16,
    has_modrm: bool,
};

pub const encodings = &[_]Enc{
    .{ .mnemonic = "fadd",   .opcode = 0xD8C0, .has_modrm = false },
    .{ .mnemonic = "fld",    .opcode = 0xD9C0, .has_modrm = false },
    .{ .mnemonic = "fst",    .opcode = 0xDDD0, .has_modrm = false },
    .{ .mnemonic = "fstp",   .opcode = 0xDDD8, .has_modrm = false },
    .{ .mnemonic = "fcom",   .opcode = 0xD8D0, .has_modrm = false },
    .{ .mnemonic = "fcomp",  .opcode = 0xD8D8, .has_modrm = false },
    .{ .mnemonic = "fchs",   .opcode = 0xD9E0, .has_modrm = false },
    .{ .mnemonic = "fabs",   .opcode = 0xD9E1, .has_modrm = false },
    .{ .mnemonic = "ftst",   .opcode = 0xD9E4, .has_modrm = false },
    .{ .mnemonic = "fxam",   .opcode = 0xD9E5, .has_modrm = false },
    .{ .mnemonic = "fld1",   .opcode = 0xD9E8, .has_modrm = false },
    .{ .mnemonic = "fldl2t", .opcode = 0xD9E9, .has_modrm = false },
    .{ .mnemonic = "fldl2e", .opcode = 0xD9EA, .has_modrm = false },
    .{ .mnemonic = "fldpi",  .opcode = 0xD9EB, .has_modrm = false },
    .{ .mnemonic = "fldlg2", .opcode = 0xD9EC, .has_modrm = false },
    .{ .mnemonic = "fldln2", .opcode = 0xD9ED, .has_modrm = false },
    .{ .mnemonic = "fldz",   .opcode = 0xD9EE, .has_modrm = false },
    .{ .mnemonic = "f2xm1",  .opcode = 0xD9F0, .has_modrm = false },
    .{ .mnemonic = "fyl2x",  .opcode = 0xD9F1, .has_modrm = false },
    .{ .mnemonic = "fptan",  .opcode = 0xD9F2, .has_modrm = false },
    .{ .mnemonic = "fpatan", .opcode = 0xD9F3, .has_modrm = false },
    .{ .mnemonic = "fxtract", .opcode = 0xD9F4, .has_modrm = false },
    .{ .mnemonic = "fprem1", .opcode = 0xD9F5, .has_modrm = false },
    .{ .mnemonic = "fdecstp", .opcode = 0xD9F6, .has_modrm = false },
    .{ .mnemonic = "fincstp", .opcode = 0xD9F7, .has_modrm = false },
    .{ .mnemonic = "fprem",  .opcode = 0xD9F8, .has_modrm = false },
    .{ .mnemonic = "fyl2xp1", .opcode = 0xD9F9, .has_modrm = false },
    .{ .mnemonic = "fsqrt",  .opcode = 0xD9FA, .has_modrm = false },
    .{ .mnemonic = "fsincos", .opcode = 0xD9FB, .has_modrm = false },
    .{ .mnemonic = "frndint", .opcode = 0xD9FC, .has_modrm = false },
    .{ .mnemonic = "fscale", .opcode = 0xD9FD, .has_modrm = false },
    .{ .mnemonic = "fsin",   .opcode = 0xD9FE, .has_modrm = false },
    .{ .mnemonic = "fcos",   .opcode = 0xD9FF, .has_modrm = false },
    .{ .mnemonic = "fnop",   .opcode = 0xD9D0, .has_modrm = false },
    .{ .mnemonic = "fwait",  .opcode = 0x9B,   .has_modrm = false },
    .{ .mnemonic = "fclex",  .opcode = 0xDBE2, .has_modrm = false },
    .{ .mnemonic = "finit",  .opcode = 0xDBE3, .has_modrm = false },
    .{ .mnemonic = "fbld",   .opcode = 0xDF,   .has_modrm = true },
    .{ .mnemonic = "fbstp",  .opcode = 0xDF,   .has_modrm = true },
    .{ .mnemonic = "fxch",   .opcode = 0xD9C8, .has_modrm = false },
    .{ .mnemonic = "ffree",  .opcode = 0xDDC0, .has_modrm = false },
};

pub fn findByMnemonic(mnemonic: []const u8) ?Enc {
    for (encodings) |e| {
        if (std.mem.eql(u8, e.mnemonic, mnemonic)) return e;
    }
    return null;
}
