[window]
width = 240
height = 290
title = "Minesweeper"
gdi = 1

[global]
framebuffer_logger = false
framebuffer_log_dir = "src/graphics/fb-logger/log"

[debug]
enabled = true
x86_disasm = true
graphics_layout = true
first_frame_dump = true
runtime_abi_fail_fast = true
log_file = "rosette-x86.log"
