[debug]
enabled = true
x86_disasm = true
graphics_layout = true
first_frame_dump = true
runtime_abi_fail_fast = true
log_file = "rosette-x86.log"

[window]
gdi = 1
title = "Console Tetris"
width = 565
height = 850
